I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 130, in script
    cs "*pop* Noice! Genergy is 2 for $5! I'll take them all!"
Exception: Sayer 'cashier' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 130, in script
    cs "*pop* Noice! Genergy is 2 for $5! I'll take them all!"
  File "C:\Users\AWK\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\AWK\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'cashier' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
CS Bounciness Vol. 3 1.0
Tue Feb 25 20:52:38 2020
